/* ==========================================================================
   A FARM — PRODUCT CATALOG (shared data)
   Loaded by BOTH index.html (customer app) and admin.html (admin panel)
   so there is exactly one source of truth for products. Edit this file
   to add/remove catalog items. Live price/stock overrides made from the
   admin panel are stored separately in localStorage and layered on top
   at runtime — they do NOT edit this file.
   ==========================================================================
   ========================================================================== */

/* ---------------------------------------------------------------------
   CATEGORY METADATA
--------------------------------------------------------------------- */
const CATEGORIES = [
  { key: "vegetables", label: "Vegetables",        emoji: "🥦" },
  { key: "tomatoes",   label: "Tomatoes",           emoji: "🍅" },
  { key: "peppers",    label: "Peppers & Chilies",  emoji: "🌶️" },
  { key: "root",       label: "Root Vegetables",    emoji: "🥕" },
  { key: "squash",     label: "Squash & Zucchini",  emoji: "🥒" },
  { key: "beans",      label: "Beans",               emoji: "🫘" },
  { key: "okra",       label: "Okra",                emoji: "🌾" },
  { key: "potatoes",   label: "Potatoes",            emoji: "🥔" },
  { key: "herbs",      label: "Herbs & Leaves",      emoji: "🌿" },
  { key: "fruits",     label: "Fruits",              emoji: "🍑" },
  { key: "flowers",    label: "Flowers",             emoji: "🌸" },
  { key: "seeds",      label: "Seeds",               emoji: "🌰" },
  { key: "baskets",    label: "Baskets",             emoji: "🧺" }
];
function categoryLabel(key){
  const c = CATEGORIES.find(c => c.key === key);
  return c ? c.label : key;
}

/* ---------------------------------------------------------------------
   PRODUCT CATALOG
   image / video left empty until real farm media is supplied.
   price: number, or null when not yet provided (see priceNote).
   available: true/false only when confirmed; otherwise availabilityNote.
   basketEligible + basketSpace configure the $30 Basket feature.
--------------------------------------------------------------------- */
const PRODUCTS = [
  // ---- TOMATOES ----
  { id:"tom-cherry",  name:"Cherry Tomatoes",         category:"tomatoes", price:5.99, unit:"quart",     available:true, featured:true,  basketEligible:true, basketSpace:2, image:"media/images/cherry-tomatoes-vine.jpg", video:"media/videos/cherry-tomato-harvest.mp4" },
  { id:"tom-bigboy",  name:"Big Boy Tomatoes",        category:"tomatoes", price:4.99, unit:"quart",     available:true, basketEligible:true, basketSpace:2, image:"media/images/tomato-ripening.jpg", video:"media/videos/tomato-ripening.mp4" },
  { id:"tom-long",    name:"Long Tomatoes",           category:"tomatoes", price:5.49, unit:"quart",     available:true, basketEligible:true, basketSpace:2 },
  { id:"tom-jelly",   name:"Jelly Bean Hybrid Tomatoes", category:"tomatoes", price:6.49, unit:"quart",  available:true, basketEligible:true, basketSpace:2 },

  // ---- PEPPERS & CHILIES ----
  { id:"pep-thai",     name:"Thai Chili",         category:"peppers", price:7.99, unit:"quart", available:true, basketEligible:true, basketSpace:1 },
  { id:"pep-jalapeno", name:"Jalapeño",           category:"peppers", price:4.99, unit:"quart", available:true, featured:true, basketEligible:true, basketSpace:1 },
  { id:"pep-indian",   name:"Indian Chili",       category:"peppers", price:7.49, unit:"quart", available:true, basketEligible:true, basketSpace:1 },
  { id:"pep-bell",     name:"Sweet Bell Pepper",  category:"peppers", price:4.99, unit:"quart", available:true, featured:true, basketEligible:true, basketSpace:1 },
  { id:"pep-habanero", name:"Habanero",           category:"peppers", price:8.99, unit:"quart", available:true, basketEligible:true, basketSpace:1 },
  { id:"pep-green",    name:"Green Chili",        category:"peppers", price:null, unit:"quart", priceNote:"Price information needed", availabilityNote:"INFORMATION NEEDED", basketEligible:false },

  // ---- VEGETABLES / GREENS ----
  { id:"veg-broccoli",   name:"Broccoli",              category:"vegetables", price:4.99, unit:"quart", available:true, seasonal:true, basketEligible:true, basketSpace:2 },
  { id:"veg-spinach",    name:"Spinach",               category:"vegetables", price:5.99, unit:"quart", available:true, basketEligible:true, basketSpace:1 },
  { id:"veg-cauliflower",name:"Cauliflower",           category:"vegetables", price:5.99, unit:"each", available:true, basketEligible:true, basketSpace:2, stockNote:"2 available" },
  { id:"veg-cucumber",   name:"Cucumber",              category:"vegetables", price:3.99, unit:"quart", available:true, featured:true, basketEligible:true, basketSpace:2 },
  { id:"veg-lettuce",    name:"Lettuce Varieties",     category:"vegetables", price:null, unit:"quart", priceNote:"Price information needed", availabilityNote:"INFORMATION NEEDED", basketEligible:false },
  { id:"veg-cabbage",    name:"Cabbage",               category:"vegetables", price:null, unit:"quart", priceNote:"Price information needed", availabilityNote:"INFORMATION NEEDED", basketEligible:false, image:"media/images/cabbage-head.jpg", video:"media/videos/cabbage-harvest.mp4" },

  // ---- ONIONS & GARLIC (organized under Vegetables) ----
  { id:"veg-garlic-mex",   name:"Mexican Garlic",     category:"vegetables", price:8.99, unit:"quart", available:true, basketEligible:true, basketSpace:1 },
  { id:"veg-garlic-am",    name:"American Garlic",    category:"vegetables", price:7.99, unit:"quart", available:true, basketEligible:true, basketSpace:1 },
  { id:"veg-onion-red",    name:"Red Onion",          category:"vegetables", price:3.99, unit:"quart", available:true, basketEligible:true, basketSpace:1 },
  { id:"veg-onion-white",  name:"White Onion",        category:"vegetables", price:3.99, unit:"quart", available:true, basketEligible:true, basketSpace:1 },
  { id:"veg-onion-texas",  name:"Texas Yellow Onion", category:"vegetables", price:4.49, unit:"quart", available:true, basketEligible:true, basketSpace:1 },

  // ---- EGGPLANT (organized under Vegetables) ----
  { id:"veg-eggplant", name:"Eggplant",          category:"vegetables", price:4.99, unit:"each", available:true, basketEligible:true, basketSpace:2, image:"media/images/eggplant-plant.jpg", video:"media/videos/eggplant-harvest.mp4" },

  // ---- SQUASH & ZUCCHINI ----
  { id:"sq-yellow",   name:"Yellow Squash",        category:"squash", price:3.99, unit:"quart", available:true, basketEligible:true, basketSpace:2 },
  { id:"sq-summer",   name:"Summer Squash",        category:"squash", price:3.99, unit:"quart", available:true, basketEligible:true, basketSpace:2 },
  { id:"sq-bottle",   name:"Bottle Gourd",         category:"squash", price:5.99, unit:"each", available:true, basketEligible:true, basketSpace:4, image:"media/images/bottle-gourd-single.jpg", video:"media/videos/bottle-gourd-harvest.mp4" },
  { id:"zuc-american",name:"American Zucchini",    category:"squash", price:3.99, unit:"quart", available:true, seasonal:true, basketEligible:true, basketSpace:2 },
  { id:"zuc-indian",  name:"Indian Zucchini",       category:"squash", price:4.49, unit:"quart", available:true, basketEligible:true, basketSpace:2 },
  { id:"zuc-darkgreen",name:"Dark Green Zucchini",  category:"squash", price:3.99, unit:"quart", available:true, basketEligible:true, basketSpace:2 },
  { id:"zuc-black",   name:"Black Zucchini",        category:"squash", price:4.49, unit:"quart", available:true, basketEligible:true, basketSpace:2 },

  // ---- GOURDS ----
  // (Cese Loofah Gourd and Early Asian Loofah removed — not actually grown/sold.
  //  Bottle Gourd lives under Squash & Zucchini below.)

  // ---- ROOT VEGETABLES ----
  { id:"root-carrot", name:"Carrot",     category:"root", price:3.99, unit:"quart", available:true, featured:true, basketEligible:true, basketSpace:2 },
  { id:"root-radred", name:"Red Radish", category:"root", price:4.99, unit:"quart", available:true, basketEligible:true, basketSpace:1 },
  { id:"root-radwhite",name:"White Radish", category:"root", price:4.99, unit:"quart", available:true, basketEligible:true, basketSpace:1 },
  { id:"root-beets",  name:"Beets",      category:"root", price:4.99, unit:"quart", available:true, basketEligible:true, basketSpace:2 },

  // ---- HERBS & LEAVES ----
  { id:"herb-basil",    name:"Basil",           category:"herbs", price:9.99,  unit:"quart", available:true, featured:true, basketEligible:true, basketSpace:1 },
  { id:"herb-cilantro", name:"Cilantro",        category:"herbs", price:7.99,  unit:"quart", available:true, basketEligible:true, basketSpace:1 },
  { id:"herb-coriander",name:"Coriander",       category:"herbs", price:7.99,  unit:"quart", available:true, basketEligible:true, basketSpace:1 },
  { id:"herb-dill",     name:"Dill",            category:"herbs", price:8.99,  unit:"quart", available:true, basketEligible:true, basketSpace:1 },
  { id:"herb-mint",     name:"Mint",            category:"herbs", price:8.99,  unit:"quart", available:true, basketEligible:true, basketSpace:1 },
  { id:"herb-lavender", name:"Lavender",        category:"herbs", price:12.99, unit:"quart", available:true, basketEligible:true, basketSpace:1 },
  { id:"herb-thyme",    name:"Thyme",           category:"herbs", price:9.99,  unit:"quart", available:true, basketEligible:true, basketSpace:1 },
  { id:"herb-lemongrass",name:"Lemongrass",     category:"herbs", price:8.99,  unit:"quart", available:true, basketEligible:true, basketSpace:1 },
  { id:"herb-curry",    name:"Curry Leaves",    category:"herbs", price:12.99, unit:"quart", available:true, basketEligible:true, basketSpace:1 },
  { id:"herb-moringa",  name:"Moringa Leaves",  category:"herbs", price:9.99,  unit:"quart", available:true, basketEligible:true, basketSpace:1 },
  { id:"herb-parsley",  name:"Italian Parsley", category:"herbs", price:8.99,  unit:"quart", available:true, basketEligible:true, basketSpace:1 },
  { id:"herb-aloe",     name:"Aloe Leaves",     category:"herbs", price:4.99,  unit:"quart", available:true, basketEligible:true, basketSpace:1 },

  // ---- FRUITS ----
  { id:"fr-strawberry", name:"Strawberries",         category:"fruits", price:6.99,  unit:"quart",   available:true, featured:true, basketEligible:true, basketSpace:2 },
  { id:"fr-raspberry",  name:"Raspberries",          category:"fruits", price:9.99,  unit:"quart",   available:true, basketEligible:true, basketSpace:2 },
  { id:"fr-pear",       name:"Pear",                 category:"fruits", price:4.99,  unit:"quart",   available:true, basketEligible:true, basketSpace:2 },
  { id:"fr-peach",      name:"Peach",                category:"fruits", price:5.99,  unit:"quart",   available:true, seasonal:true, basketEligible:true, basketSpace:2 },
  { id:"fr-cantaloupe", name:"Cantaloupe",           category:"fruits", price:4.99,  unit:"quart",   available:true, seasonal:true, basketEligible:true, basketSpace:3 },
  { id:"fr-watermelon", name:"Watermelon",           category:"fruits", price:7.99,  unit:"each", available:true, featured:true, basketEligible:true, basketSpace:4 },
  { id:"fr-blackdiamond",name:"Black Diamond Watermelon", category:"fruits", price:12.99, unit:"each", available:true, basketEligible:true, basketSpace:4 },
  { id:"fr-pumpkin",    name:"Pumpkin",              category:"fruits", price:8.99,  unit:"each", available:true, basketEligible:true, basketSpace:4 },
  { id:"fr-lemon",      name:"Lemons",               category:"fruits", price:3.99,  unit:"quart",   available:true, basketEligible:true, basketSpace:1 },

  // ---- OKRA ----
  { id:"okra-crimson", name:"Crimson Okra", category:"okra", price:5.99, unit:"quart", available:true, seasonal:true, basketEligible:true, basketSpace:2 },
  { id:"okra-emerald", name:"Emerald Okra", category:"okra", price:5.99, unit:"quart", available:true, basketEligible:true, basketSpace:2, image:"media/images/okra-pods.jpg", video:"media/videos/okra-harvest.mp4" },

  // ---- POTATOES ----
  { id:"pot-red",   name:"Red Potatoes",   category:"potatoes", price:3.99, unit:"quart", available:true, basketEligible:true, basketSpace:2 },
  { id:"pot-white", name:"White Potatoes", category:"potatoes", price:3.99, unit:"quart", available:true, basketEligible:true, basketSpace:2 },

  // ---- BEANS ----
  { id:"bean-green", name:"Green Beans",         category:"beans", price:4.99, unit:"quart", available:true, seasonal:true, basketEligible:true, basketSpace:1, image:"media/images/green-beans-harvest.jpg", video:"media/videos/green-beans-harvest.mp4" },
  { id:"bean-lima",  name:"Lima Beans",          category:"beans", price:5.99, unit:"quart", available:true, basketEligible:true, basketSpace:1 },
  { id:"bean-guar",  name:"Guar Cluster Beans",  category:"beans", price:5.99, unit:"quart", available:true, basketEligible:true, basketSpace:1 },

  // ---- SEEDS (not basket-eligible) ----
  { id:"seed-moringa-std", name:"Standard Moringa Seeds",        category:"seeds", price:6.99, unit:"packet", available:true, basketEligible:false },
  { id:"seed-moringa-black",name:"Matured Black Moringa Seeds",  category:"seeds", price:8.99, unit:"packet", available:true, basketEligible:false },

  // ---- FLOWERS (no invented prices; not confirmed as currently grown) ----
  { id:"fl-roses",     name:"Roses",                 category:"flowers", price:null, priceNote:"Price available at farm", availabilityNote:"INFORMATION NEEDED", basketEligible:false },
  { id:"fl-sunflowers",name:"Sunflowers",             category:"flowers", price:null, priceNote:"Price available at farm", availabilityNote:"INFORMATION NEEDED", basketEligible:false },
  { id:"fl-marigolds", name:"Marigolds",              category:"flowers", price:null, priceNote:"Price available at farm", availabilityNote:"INFORMATION NEEDED", basketEligible:false },
  { id:"fl-zinnias",   name:"Zinnias",                category:"flowers", price:null, priceNote:"Price available at farm", availabilityNote:"INFORMATION NEEDED", basketEligible:false },
  { id:"fl-cosmos",    name:"Cosmos",                 category:"flowers", price:null, priceNote:"Price available at farm", availabilityNote:"INFORMATION NEEDED", basketEligible:false },
  { id:"fl-dahlias",   name:"Dahlias",                category:"flowers", price:null, priceNote:"Price available at farm", availabilityNote:"INFORMATION NEEDED", basketEligible:false },
  { id:"fl-lavenderfl",name:"Lavender Flowers",       category:"flowers", price:null, priceNote:"Price available at farm", availabilityNote:"INFORMATION NEEDED", basketEligible:false },
  { id:"fl-wildflowers",name:"Wildflowers",           category:"flowers", price:null, priceNote:"Price available at farm", availabilityNote:"INFORMATION NEEDED", basketEligible:false },
  { id:"fl-bouquets",  name:"Mixed Flower Bouquets",  category:"flowers", price:null, priceNote:"Price available at farm", availabilityNote:"INFORMATION NEEDED", basketEligible:false },
  { id:"fl-seasonal",  name:"Seasonal Flowers",       category:"flowers", price:null, priceNote:"Price available at farm", availabilityNote:"INFORMATION NEEDED", basketEligible:false },
  { id:"fl-bundles",   name:"Flower Bundles",         category:"flowers", price:null, priceNote:"Price available at farm", availabilityNote:"INFORMATION NEEDED", basketEligible:false },

  // ---- BASKETS ----
  { id:"basket-30", name:"$30 Farm Basket", category:"baskets", price:30, unit:"basket", available:true, basketEligible:false, isBasketProduct:true }
];
