/* ==========================================================================
   A FARM — PRODUCT CATALOG (shared data)
   Loaded by BOTH index.html (customer app) and admin.html (admin panel)
   so there is exactly one source of truth for products. Edit this file
   to add/remove catalog items. Live price/stock overrides made from the
   admin panel are stored separately in localStorage and layered on top
   at runtime — they do NOT edit this file.

   Trimmed to only what the farm is currently selling (per owner request).
   ========================================================================== */

/* ---------------------------------------------------------------------
   CATEGORY METADATA
--------------------------------------------------------------------- */
const CATEGORIES = [
  { key: "tomatoes",   label: "Tomatoes",           emoji: "🍅" },
  { key: "peppers",    label: "Peppers & Chilies",  emoji: "🌶️" },
  { key: "vegetables", label: "Vegetables",         emoji: "🥦" },
  { key: "squash",     label: "Squash & Zucchini",  emoji: "🥒" },
  { key: "beans",      label: "Beans",              emoji: "🫘" },
  { key: "okra",       label: "Okra",               emoji: "🌾" },
  { key: "herbs",      label: "Herbs & Leaves",     emoji: "🌿" },
  { key: "baskets",    label: "Baskets",            emoji: "🧺" }
];
function categoryLabel(key){
  const c = CATEGORIES.find(c => c.key === key);
  return c ? c.label : key;
}

/* ---------------------------------------------------------------------
   PRODUCT CATALOG
   image / video left empty until real farm media is supplied.
   price: number, or null when not yet provided (see priceNote).
   available: true/false only when confirmed; otherwise availabilityNote.
   basketEligible + basketSpace configure the $30 Basket feature.
--------------------------------------------------------------------- */
const PRODUCTS = [
  // ---- TOMATOES ----
  { id:"tom-cherry",  name:"Cherry Tomatoes",         category:"tomatoes", price:5.99, unit:"quart", available:true, featured:true, basketEligible:true, basketSpace:2, image:"media/images/cherry-tomatoes-vine.jpg", video:"media/videos/cherry-tomato-harvest.mp4" },
  { id:"tom-bigboy",  name:"Big Boy Tomatoes",        category:"tomatoes", price:4.99, unit:"quart", available:true, basketEligible:true, basketSpace:2, image:"media/images/tomato-ripening.jpg", video:"media/videos/tomato-ripening.mp4" },
  { id:"tom-long",    name:"Long Tomatoes",           category:"tomatoes", price:5.49, unit:"quart", available:true, basketEligible:true, basketSpace:2 },
  { id:"tom-jelly",   name:"Jelly Bean Hybrid Tomatoes", category:"tomatoes", price:6.49, unit:"quart", available:true, basketEligible:true, basketSpace:2 },

  // ---- PEPPERS & CHILIES ----
  { id:"pep-thai",     name:"Thai Chili",         category:"peppers", price:7.99, unit:"quart", available:true, basketEligible:true, basketSpace:1 },
  { id:"pep-jalapeno", name:"Jalapeño",           category:"peppers", price:4.99, unit:"quart", available:true, featured:true, basketEligible:true, basketSpace:1 },
  { id:"pep-indian",   name:"Indian Chili",       category:"peppers", price:7.49, unit:"quart", available:true, basketEligible:true, basketSpace:1 },
  { id:"pep-bell",     name:"Sweet Bell Pepper",  category:"peppers", price:4.99, unit:"quart", available:true, featured:true, basketEligible:true, basketSpace:1 },
  { id:"pep-habanero", name:"Habanero",           category:"peppers", price:8.99, unit:"quart", available:true, basketEligible:true, basketSpace:1 },
  { id:"pep-green",    name:"Green Chili",        category:"peppers", price:null, unit:"quart", priceNote:"Price information needed", availabilityNote:"INFORMATION NEEDED", basketEligible:false },

  // ---- VEGETABLES ----
  { id:"veg-cabbage",  name:"Cabbage",             category:"vegetables", price:null, unit:"quart", priceNote:"Price information needed", availabilityNote:"INFORMATION NEEDED", basketEligible:false, image:"media/images/cabbage-head.jpg", video:"media/videos/cabbage-harvest.mp4" },
  { id:"veg-eggplant", name:"Eggplant",            category:"vegetables", price:4.99, unit:"each", available:true, basketEligible:true, basketSpace:2, image:"media/images/eggplant-plant.jpg", video:"media/videos/eggplant-harvest.mp4" },
  { id:"veg-karela",   name:"Karela (Bitter Melon)",category:"vegetables", price:5.99, unit:"quart", available:true, basketEligible:true, basketSpace:2, image:"media/images/gourd-trellis-looking-up.jpg", video:"media/videos/cese-loofah-harvest.mp4" },

  // ---- SQUASH & ZUCCHINI ----
  { id:"sq-bottle",    name:"Bottle Gourd",         category:"squash", price:5.99, unit:"each", available:true, basketEligible:true, basketSpace:4, image:"media/images/bottle-gourd-single.jpg", video:"media/videos/bottle-gourd-harvest.mp4" },
  { id:"zuc-american", name:"American Zucchini",    category:"squash", price:3.99, unit:"quart", available:true, seasonal:true, basketEligible:true, basketSpace:2 },
  { id:"zuc-indian",   name:"Indian Zucchini",      category:"squash", price:4.49, unit:"quart", available:true, basketEligible:true, basketSpace:2 },
  { id:"zuc-darkgreen",name:"Dark Green Zucchini",  category:"squash", price:3.99, unit:"quart", available:true, basketEligible:true, basketSpace:2 },
  { id:"zuc-black",    name:"Black Zucchini",       category:"squash", price:4.49, unit:"quart", available:true, basketEligible:true, basketSpace:2 },

  // ---- BEANS ----
  { id:"bean-green", name:"Green Beans",         category:"beans", price:4.99, unit:"quart", available:true, seasonal:true, basketEligible:true, basketSpace:1, image:"media/images/green-beans-harvest.jpg", video:"media/videos/green-beans-harvest.mp4" },
  { id:"bean-lima",  name:"Lima Beans",          category:"beans", price:5.99, unit:"quart", available:true, basketEligible:true, basketSpace:1 },
  { id:"bean-guar",  name:"Guar Cluster Beans",  category:"beans", price:5.99, unit:"quart", available:true, basketEligible:true, basketSpace:1 },

  // ---- OKRA ----
  { id:"okra-crimson", name:"Crimson Okra", category:"okra", price:5.99, unit:"quart", available:true, seasonal:true, basketEligible:true, basketSpace:2 },
  { id:"okra-emerald", name:"Emerald Okra", category:"okra", price:5.99, unit:"quart", available:true, basketEligible:true, basketSpace:2, image:"media/images/okra-pods.jpg", video:"media/videos/okra-harvest.mp4" },

  // ---- HERBS & LEAVES ----
  { id:"herb-lemongrass", name:"Lemongrass", category:"herbs", price:8.99, unit:"quart", available:true, basketEligible:true, basketSpace:1 },
  { id:"herb-mint",       name:"Mint",       category:"herbs", price:8.99, unit:"quart", available:true, featured:true, basketEligible:true, basketSpace:1 },

  // ---- BASKETS ----
  { id:"basket-30", name:"$30 Farm Basket", category:"baskets", price:30, unit:"basket", available:true, basketEligible:false, isBasketProduct:true }
];
