/* ==========================================================================
   A FARM — PRODUCT CATALOG (shared data)
   Loaded by BOTH index.html (customer app) and admin.html (admin panel)
   so there is exactly one source of truth for products. Edit this file
   to add/remove catalog items. Live price/stock overrides made from the
   admin panel are stored separately in localStorage and layered on top
   at runtime — they do NOT edit this file.

   Trimmed to only what the farm is currently selling (per owner request).
   "description" is general, widely-known produce info (taste/texture/
   uses) — not a claim about this specific farm's growing practices.
   ========================================================================== */

/* ---------------------------------------------------------------------
   CATEGORY METADATA
--------------------------------------------------------------------- */
const CATEGORIES = [
  { key: "tomatoes",   label: "Tomatoes",           emoji: "🍅" },
  { key: "peppers",    label: "Peppers & Chilies",  emoji: "🌶️" },
  { key: "vegetables", label: "Vegetables",         emoji: "🥦" },
  { key: "squash",     label: "Squash & Zucchini",  emoji: "🥒" },
  { key: "beans",      label: "Beans",              emoji: "🫘" },
  { key: "okra",       label: "Okra",               emoji: "🌾" },
  { key: "herbs",      label: "Herbs & Leaves",     emoji: "🌿" },
  { key: "baskets",    label: "Baskets",            emoji: "🧺" }
];
function categoryLabel(key){
  const c = CATEGORIES.find(c => c.key === key);
  return c ? c.label : key;
}

/* ---------------------------------------------------------------------
   PRODUCT CATALOG
   image / video left empty until real farm media is supplied.
   price: number, or null when not yet provided (see priceNote).
   available: true/false only when confirmed; otherwise availabilityNote.
   basketEligible + basketSpace configure the $30 Basket feature.
--------------------------------------------------------------------- */
const PRODUCTS = [
  // ---- TOMATOES ----
  { id:"tom-cherry",  name:"Cherry Tomatoes",         category:"tomatoes", price:5.99, unit:"quart", available:true, featured:true, basketEligible:true, basketSpace:2, image:"cherry-tomatoes-vine.jpg", video:"cherry-tomato-harvest.mp4",
    description:"Small, sweet, and juicy with thin skins — good for snacking, salads, or roasting whole. A source of vitamin C." },
  { id:"tom-bigboy",  name:"Big Boy Tomatoes",        category:"tomatoes", price:4.99, unit:"quart", available:true, basketEligible:true, basketSpace:2, image:"tomato-ripening.jpg", video:"tomato-ripening.mp4",
    description:"A classic slicing tomato — meaty, mildly sweet, and juicy. Good on sandwiches, burgers, or in a fresh salad." },
  { id:"tom-long",    name:"Long Tomatoes",           category:"tomatoes", price:5.49, unit:"quart", available:true, basketEligible:true, basketSpace:2,
    description:"Elongated and firm-fleshed with fewer seeds than round tomatoes, holding their shape well when cooked into sauces." },
  { id:"tom-jelly",   name:"Jelly Bean Hybrid Tomatoes", category:"tomatoes", price:6.49, unit:"quart", available:true, basketEligible:true, basketSpace:2,
    description:"A small, oblong grape-type tomato with a sweet, candy-like bite — good for snacking or tossing into salads." },

  // ---- PEPPERS & CHILIES ----
  { id:"pep-thai",     name:"Thai Chili",         category:"peppers", price:7.99, unit:"quart", available:true, basketEligible:true, basketSpace:1,
    description:"Small, thin, and very hot with a sharp, bright heat. Common in Southeast Asian cooking — use sparingly in stir-fries, soups, or sauces." },
  { id:"pep-jalapeno", name:"Jalapeño",           category:"peppers", price:4.99, unit:"quart", available:true, featured:true, basketEligible:true, basketSpace:1,
    description:"Medium heat with a crisp, grassy flavor. Good fresh in salsa, sliced on nachos, or roasted." },
  { id:"pep-indian",   name:"Indian Chili",       category:"peppers", price:7.49, unit:"quart", available:true, basketEligible:true, basketSpace:1,
    description:"Slender and fiery, used fresh or dried in Indian cooking to add heat to curries, chutneys, and pickles." },
  { id:"pep-bell",     name:"Sweet Bell Pepper",  category:"peppers", price:4.99, unit:"quart", available:true, featured:true, basketEligible:true, basketSpace:1,
    description:"Crisp, juicy, and mild with no heat. Good raw in salads or cooked in stir-fries. A source of vitamin C." },
  { id:"pep-habanero", name:"Habanero",           category:"peppers", price:8.99, unit:"quart", available:true, basketEligible:true, basketSpace:1,
    description:"Very hot with a fruity, floral note. Use in small amounts in salsas, hot sauces, or marinades." },
  { id:"pep-green",    name:"Green Chili",        category:"peppers", price:null, unit:"quart", priceNote:"Price information needed", availabilityNote:"INFORMATION NEEDED", basketEligible:false, image:"green-chili-plant.jpg", video:"green-chili-harvest.mp4",
    description:"A slender, medium-hot green chili used fresh for a sharp, grassy heat in cooking." },

  // ---- VEGETABLES ----
  { id:"veg-cabbage",  name:"Cabbage",             category:"vegetables", price:null, unit:"quart", priceNote:"Price information needed", availabilityNote:"INFORMATION NEEDED", basketEligible:false, image:"cabbage-head.jpg", video:"cabbage-harvest.mp4",
    description:"Crisp and mild with a slight peppery bite raw, sweeter when cooked. Good in slaws, stir-fries, or soups." },
  { id:"veg-eggplant", name:"Eggplant",            category:"vegetables", price:4.99, unit:"each", available:true, basketEligible:true, basketSpace:2, image:"eggplant-plant.jpg", video:"eggplant-harvest.mp4",
    description:"Tender with a mild, slightly earthy flavor that takes on seasoning well. Good roasted, grilled, or in curries." },
  { id:"veg-karela",   name:"Karela (Bitter Melon)",category:"vegetables", price:5.99, unit:"quart", available:true, basketEligible:true, basketSpace:2, image:"karela-closeup.jpg", video:"cese-loofah-harvest.mp4",
    description:"Distinctly bitter with a crunchy texture. A staple in South Asian cooking, often stir-fried with onions and spices to balance the bitterness." },

  // ---- SQUASH & ZUCCHINI ----
  { id:"sq-bottle",    name:"Bottle Gourd",         category:"squash", price:5.99, unit:"each", available:true, basketEligible:true, basketSpace:4, image:"bottle-gourd-single.jpg", video:"bottle-gourd-harvest.mp4",
    description:"Mild and mellow with a soft texture once cooked. Commonly used in soups, curries, and stews." },
  { id:"zuc-american", name:"American Zucchini",    category:"squash", price:3.99, unit:"quart", available:true, seasonal:true, basketEligible:true, basketSpace:2,
    description:"Mild, tender, and slightly sweet — good sautéed, grilled, or baked into breads." },
  { id:"zuc-indian",   name:"Indian Zucchini",      category:"squash", price:4.49, unit:"quart", available:true, basketEligible:true, basketSpace:2,
    description:"Light and mild-flavored with tender flesh, well suited to curries and stir-fries." },
  { id:"zuc-darkgreen",name:"Dark Green Zucchini",  category:"squash", price:3.99, unit:"quart", available:true, basketEligible:true, basketSpace:2,
    description:"Firm and mild-tasting, holds up well to grilling or roasting." },
  { id:"zuc-black",    name:"Black Zucchini",       category:"squash", price:4.49, unit:"quart", available:true, basketEligible:true, basketSpace:2,
    description:"Deep-skinned and mild, tender when cooked — versatile in stir-fries or baked dishes." },

  // ---- BEANS ----
  { id:"bean-green", name:"Green Beans",         category:"beans", price:4.99, unit:"quart", available:true, seasonal:true, basketEligible:true, basketSpace:1, image:"green-beans-harvest.jpg", video:"green-beans-harvest.mp4",
    description:"Crisp and snappy with a fresh, grassy flavor. Good steamed, sautéed, or added to stir-fries. A source of fiber." },
  { id:"bean-lima",  name:"Lima Beans",          category:"beans", price:5.99, unit:"quart", available:true, basketEligible:true, basketSpace:1,
    description:"Starchy and creamy once cooked, with a mild, buttery flavor — good in soups and stews." },
  { id:"bean-guar",  name:"Guar Cluster Beans",  category:"beans", price:5.99, unit:"quart", available:true, basketEligible:true, basketSpace:1,
    description:"Firm, slightly fibrous pods with an earthy flavor, popular in Indian stir-fries and curries." },

  // ---- OKRA ----
  { id:"okra-crimson", name:"Crimson Okra", category:"okra", price:5.99, unit:"quart", available:true, seasonal:true, basketEligible:true, basketSpace:2,
    description:"Tender pods with a mild, slightly grassy flavor — good sautéed, roasted, or added to stews." },
  { id:"okra-emerald", name:"Emerald Okra", category:"okra", price:5.99, unit:"quart", available:true, basketEligible:true, basketSpace:2, image:"okra-pods.jpg", video:"okra-harvest.mp4",
    description:"Crisp and mild, becomes tender when cooked — a common addition to gumbo, curries, and stir-fries." },

  // ---- HERBS & LEAVES ----
  { id:"herb-lemongrass", name:"Lemongrass", category:"herbs", price:8.99, unit:"quart", available:true, basketEligible:true, basketSpace:1,
    description:"Citrusy and aromatic, used to infuse soups, teas, and marinades with a bright lemon flavor." },
  { id:"herb-mint",       name:"Mint",       category:"herbs", price:8.99, unit:"quart", available:true, featured:true, basketEligible:true, basketSpace:1,
    description:"Cool, refreshing, and aromatic — good in teas, salads, and as a garnish." },

  // ---- BASKETS ----
  { id:"basket-30", name:"$30 Farm Basket", category:"baskets", price:30, unit:"basket", available:true, basketEligible:false, isBasketProduct:true,
    description:"Fill a basket with whatever fits from the eligible produce above — one flat $30 price no matter what you pick." }
];
